# Generated by Django 3.2.3 on 2021-05-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="tite",
            new_name="title",
        ),
    ]
